In [1]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [2]:
schalar=torch.tensor(7)
schalar

tensor(7)

In [3]:
schalar.item()

7

In [9]:
vector=torch.tensor([[1, 2, 3], [4,5,6]])
vector

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
vector.shape

torch.Size([2, 3])

In [11]:
vector.ndim

2

In [14]:
vector[1][0]

tensor(4)

In [15]:
## Random tensor

In [17]:
random_tensor=torch.rand(3, 4)
random_tensor

tensor([[0.1510, 0.8521, 0.0114, 0.4732],
        [0.3841, 0.2687, 0.9328, 0.3079],
        [0.5632, 0.7291, 0.5965, 0.1411]])

In [18]:
r_image=torch.rand(size=(224, 224, 3))
r_image.shape, r_image.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros=torch.zeros(size=(2, 2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [20]:
# range and range like

In [21]:
torch.range(0, 10)

/tmp/ipython-input-1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
one_to_ten=torch.arange(start=1, end=10, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [25]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [30]:
float_32_tensor=torch.tensor([2,3], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([2, 3])

### Manupulation

In [31]:
tensor=torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [32]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [34]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [35]:
torch.sub(tensor, 4)

tensor([-3, -2, -1])

### Matrix multiplication

In [36]:
print(tensor,  '*',tensor )
print(f'Equals: {tensor * tensor}')


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
print(torch.matmul(tensor, tensor))

tensor(14)


In [38]:
x=torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
x.type(torch.float32).mean()

tensor(45.)

In [42]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [43]:
x.argmin()


tensor(0)

In [44]:
x.argmax()

tensor(9)

In [45]:
x.argsort()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.argwhere()

In [47]:
x=torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
x.reshape(2, 5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [51]:
torch.stack([x, x, x, x ], dim=1)

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [54]:
torch.unsqueeze(x, dim=1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [58]:
y=torch.squeeze(x)
y

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
torch.squeeze(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
q=torch.rand(size=(128, 128, 3))
q_permute=q.permute(1, 2, 0)
q_permute.shape

torch.Size([128, 3, 128])

### NumPy & Tensor

In [69]:
import numpy as np
import torch
array=np.arange(1.0, 11.0)
tensor=torch.from_numpy(array)
array, tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [71]:
array=array+1
array, tensor

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [73]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
import torch
random_seed=42
r_n_a=torch.rand(3, 4)
torch.manual_seed(random_seed)
r_n_b=torch.rand(3, 4)
print(r_n_a)
print(r_n_b)
print(r_n_a==r_n_b)


tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [77]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
tensor=torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [4]:
device='cuda'

In [6]:
tensor_to_gpu=tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

### Assignment

In [14]:
import torch
tensor1=torch.rand(7, 7)
tensor, tensor.shape

(tensor([[0.6537, 0.9571, 0.1856, 0.8492, 0.0878, 0.3005, 0.8719],
         [0.9983, 0.6376, 0.3067, 0.8383, 0.6368, 0.2895, 0.9182],
         [0.1894, 0.6098, 0.3437, 0.2371, 0.9537, 0.1690, 0.9863],
         [0.2407, 0.3672, 0.5197, 0.5061, 0.8716, 0.1352, 0.8912],
         [0.2536, 0.3113, 0.2213, 0.6009, 0.0341, 0.6786, 0.5310],
         [0.2032, 0.5436, 0.7898, 0.4498, 0.4666, 0.4465, 0.7737],
         [0.6756, 0.3926, 0.0122, 0.1011, 0.4273, 0.8102, 0.9080]]),
 torch.Size([7, 7]))

In [19]:
tensor2=torch.rand(1, 7)
tensor2
torch.manual_seed(0)
output=torch.mm(tensor1, tensor2.T)
print(output)
print(output.shape)

tensor([[1.2835],
        [1.5860],
        [1.3890],
        [2.0347],
        [1.9077],
        [1.4557],
        [1.3594]])
torch.Size([7, 1])


In [20]:
tensor3=torch.rand(1, 7)
torch.manual_seed(1234)
tensor4=torch.rand(1, 7)
print(tensor3==tensor4)




tensor([[False, False, False, False, False, False, False]])


In [24]:
tensor5=torch.rand(2, 3)
tensor5_to_gpu=tensor5.to(device)
print(tensor5_to_gpu)
torch.manual_seed(1234)
tensor6=torch.rand(2, 3)
tensor6_to_gpu=tensor6.to(device)
print(tensor6_to_gpu)


tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


In [26]:
# Perform matmul on tensor_A and tensor_B
output=torch.mm(tensor5, tensor6.T)
output, output.device, output.shape

(tensor([[0.3647, 0.5184],
         [0.4709, 0.5617]]),
 device(type='cpu'),
 torch.Size([2, 2]))

In [30]:
# Find max
max=torch.max(output)

# Find min
min=torch.min(output)
max, min

(tensor(0.5617), tensor(0.3647))

In [31]:
argmax=torch.argmax(output)
argmin=torch.argmin(output)
argmax, argmin

(tensor(3), tensor(0))

In [32]:
tensor7=torch.rand(1, 1, 1, 10)
torch.manual_seed(7)
squeezed_tensor=torch.squeeze(tensor7)
tensor7, tensor7.shape, squeezed_tensor, squeezed_tensor.shape



(tensor([[[[0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208,
            0.2793, 0.6817]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208, 0.2793,
         0.6817]),
 torch.Size([10]))